/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_backslash = 1,
  sym_identifier = 2,
  anon_sym_LT = 3,
  anon_sym_SLASH = 4,
  anon_sym_GT = 5,
  sym_tag_string = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  sym_tag_text = 9,
  sym_heading = 10,
  sym_code_span = 11,
  anon_sym_LBRACE_LBRACE_LBRACE = 12,
  anon_sym_RBRACE_RBRACE_RBRACE = 13,
  anon_sym_LBRACE_LBRACE = 14,
  anon_sym_RBRACE_RBRACE = 15,
  sym_comment = 16,
  sym_text = 17,
  sym_document = 18,
  sym_command = 19,
  sym_tag = 20,
  sym_tag_expr = 21,
  sym_delimiter = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_tag_repeat1 = 24,
  aux_sym_tag_expr_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_backslash] = "backslash",
  [sym_identifier] = "identifier",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [sym_tag_string] = "tag_string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_tag_text] = "tag_text",
  [sym_heading] = "heading",
  [sym_code_span] = "code_span",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "{{{",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "}}}",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_command] = "command",
  [sym_tag] = "tag",
  [sym_tag_expr] = "tag_expr",
  [sym_delimiter] = "delimiter",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_tag_expr_repeat1] = "tag_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_backslash] = sym_backslash,
  [sym_identifier] = sym_identifier,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [sym_tag_string] = sym_tag_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_tag_text] = sym_tag_text,
  [sym_heading] = sym_heading,
  [sym_code_span] = sym_code_span,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_command] = sym_command,
  [sym_tag] = sym_tag,
  [sym_tag_expr] = sym_tag_expr,
  [sym_delimiter] = sym_delimiter,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_tag_expr_repeat1] = aux_sym_tag_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_backslash] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_text] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_marker = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_marker] = "marker",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
    {field_name, 1},
  [2] =
    {field_name, 1},
  [3] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 12,
  [16] = 13,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 6,
  [25] = 22,
  [26] = 23,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 2,
        '#', 28,
        '/', 18,
        '<', 17,
        '>', 20,
        '\\', 14,
        '`', 9,
        '{', 23,
        '}', 25,
        '\t', 4,
        ' ', 4,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 38,
        '<', 37,
        '>', 41,
        '\\', 15,
        '{', 22,
        '}', 24,
        '\n', 27,
        '#', 27,
        '`', 27,
      );
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '}') ADVANCE(35);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '`') ADVANCE(30);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '#', 28,
        '<', 17,
        '\\', 14,
        '`', 40,
        '{', 23,
        '}', 25,
        '\t', 39,
        ' ', 39,
        '\n', 37,
        '"', 37,
      );
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_backslash);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_backslash);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_tag_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '{') ADVANCE(33);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(34);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_tag_text);
      if (lookahead == '>') ADVANCE(41);
      if (lookahead == '\n' ||
          lookahead == '#' ||
          lookahead == '\\' ||
          lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_tag_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_heading);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_heading);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_code_span);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '{') ADVANCE(31);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      if (lookahead == '}') ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '`') ADVANCE(30);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_backslash] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_tag_string] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_heading] = ACTIONS(1),
    [sym_code_span] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(31),
    [sym_command] = STATE(2),
    [sym_tag] = STATE(2),
    [sym_delimiter] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_backslash] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_heading] = ACTIONS(11),
    [sym_code_span] = ACTIONS(11),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE_RBRACE_RBRACE] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
    [sym_text] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_command] = STATE(3),
    [sym_tag] = STATE(3),
    [sym_delimiter] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_backslash] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_heading] = ACTIONS(19),
    [sym_code_span] = ACTIONS(19),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE_RBRACE_RBRACE] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(9),
    [sym_comment] = ACTIONS(19),
    [sym_text] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_command] = STATE(3),
    [sym_tag] = STATE(3),
    [sym_delimiter] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_backslash] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(28),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym_heading] = ACTIONS(34),
    [sym_code_span] = ACTIONS(34),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(37),
    [anon_sym_RBRACE_RBRACE_RBRACE] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(31),
    [sym_comment] = ACTIONS(34),
    [sym_text] = ACTIONS(40),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(45), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(43), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [18] = 2,
    ACTIONS(49), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(47), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [36] = 2,
    ACTIONS(53), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(51), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [54] = 2,
    ACTIONS(57), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [72] = 2,
    ACTIONS(61), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [90] = 2,
    ACTIONS(65), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(63), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [108] = 2,
    ACTIONS(69), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(67), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [126] = 2,
    ACTIONS(73), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      sym_text,
    ACTIONS(71), 8,
      ts_builtin_sym_end,
      sym_backslash,
      anon_sym_LT,
      sym_heading,
      sym_code_span,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      sym_comment,
  [144] = 6,
    ACTIONS(75), 1,
      sym_backslash,
    ACTIONS(77), 1,
      sym_tag_string,
    ACTIONS(79), 1,
      anon_sym_LBRACE,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 2,
      sym_tag_text,
      sym_text,
    STATE(13), 3,
      sym_command,
      sym_tag_expr,
      aux_sym_tag_expr_repeat1,
  [166] = 6,
    ACTIONS(75), 1,
      sym_backslash,
    ACTIONS(79), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      sym_tag_string,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 2,
      sym_tag_text,
      sym_text,
    STATE(14), 3,
      sym_command,
      sym_tag_expr,
      aux_sym_tag_expr_repeat1,
  [188] = 6,
    ACTIONS(91), 1,
      sym_backslash,
    ACTIONS(94), 1,
      sym_tag_string,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(102), 2,
      sym_tag_text,
      sym_text,
    STATE(14), 3,
      sym_command,
      sym_tag_expr,
      aux_sym_tag_expr_repeat1,
  [210] = 6,
    ACTIONS(75), 1,
      sym_backslash,
    ACTIONS(79), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 1,
      sym_tag_string,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(109), 2,
      sym_tag_text,
      sym_text,
    STATE(16), 3,
      sym_command,
      sym_tag_expr,
      aux_sym_tag_expr_repeat1,
  [232] = 6,
    ACTIONS(75), 1,
      sym_backslash,
    ACTIONS(79), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      sym_tag_string,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 2,
      sym_tag_text,
      sym_text,
    STATE(14), 3,
      sym_command,
      sym_tag_expr,
      aux_sym_tag_expr_repeat1,
  [254] = 6,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_GT,
    ACTIONS(117), 1,
      sym_tag_string,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      sym_tag_text,
    STATE(21), 2,
      sym_tag_expr,
      aux_sym_tag_repeat1,
  [274] = 6,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(127), 1,
      sym_tag_string,
    ACTIONS(129), 1,
      sym_tag_text,
    STATE(20), 2,
      sym_tag_expr,
      aux_sym_tag_repeat1,
  [294] = 6,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(133), 1,
      anon_sym_GT,
    ACTIONS(135), 1,
      sym_tag_string,
    ACTIONS(137), 1,
      sym_tag_text,
    STATE(18), 2,
      sym_tag_expr,
      aux_sym_tag_repeat1,
  [314] = 6,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_GT,
    ACTIONS(143), 1,
      sym_tag_string,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      sym_tag_text,
    STATE(20), 2,
      sym_tag_expr,
      aux_sym_tag_repeat1,
  [334] = 6,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      sym_tag_string,
    ACTIONS(129), 1,
      sym_tag_text,
    ACTIONS(152), 1,
      anon_sym_SLASH,
    ACTIONS(154), 1,
      anon_sym_GT,
    STATE(20), 2,
      sym_tag_expr,
      aux_sym_tag_repeat1,
  [354] = 2,
    ACTIONS(156), 3,
      sym_backslash,
      sym_tag_text,
      sym_text,
    ACTIONS(158), 3,
      sym_tag_string,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [365] = 2,
    ACTIONS(160), 3,
      sym_backslash,
      sym_tag_text,
      sym_text,
    ACTIONS(162), 3,
      sym_tag_string,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [376] = 2,
    ACTIONS(51), 3,
      sym_tag_string,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(53), 3,
      sym_backslash,
      sym_tag_text,
      sym_text,
  [387] = 2,
    ACTIONS(156), 2,
      anon_sym_SLASH,
      sym_tag_text,
    ACTIONS(158), 3,
      anon_sym_GT,
      sym_tag_string,
      anon_sym_LBRACE,
  [397] = 2,
    ACTIONS(160), 2,
      anon_sym_SLASH,
      sym_tag_text,
    ACTIONS(162), 3,
      anon_sym_GT,
      sym_tag_string,
      anon_sym_LBRACE,
  [407] = 2,
    ACTIONS(164), 1,
      sym_identifier,
    ACTIONS(166), 1,
      anon_sym_SLASH,
  [414] = 1,
    ACTIONS(125), 1,
      anon_sym_GT,
  [418] = 1,
    ACTIONS(168), 1,
      sym_identifier,
  [422] = 1,
    ACTIONS(170), 1,
      sym_identifier,
  [426] = 1,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
  [430] = 1,
    ACTIONS(174), 1,
      anon_sym_GT,
  [434] = 1,
    ACTIONS(176), 1,
      anon_sym_GT,
  [438] = 1,
    ACTIONS(154), 1,
      anon_sym_GT,
  [442] = 1,
    ACTIONS(178), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 72,
  [SMALL_STATE(9)] = 90,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 126,
  [SMALL_STATE(12)] = 144,
  [SMALL_STATE(13)] = 166,
  [SMALL_STATE(14)] = 188,
  [SMALL_STATE(15)] = 210,
  [SMALL_STATE(16)] = 232,
  [SMALL_STATE(17)] = 254,
  [SMALL_STATE(18)] = 274,
  [SMALL_STATE(19)] = 294,
  [SMALL_STATE(20)] = 314,
  [SMALL_STATE(21)] = 334,
  [SMALL_STATE(22)] = 354,
  [SMALL_STATE(23)] = 365,
  [SMALL_STATE(24)] = 376,
  [SMALL_STATE(25)] = 387,
  [SMALL_STATE(26)] = 397,
  [SMALL_STATE(27)] = 407,
  [SMALL_STATE(28)] = 414,
  [SMALL_STATE(29)] = 418,
  [SMALL_STATE(30)] = 422,
  [SMALL_STATE(31)] = 426,
  [SMALL_STATE(32)] = 430,
  [SMALL_STATE(33)] = 434,
  [SMALL_STATE(34)] = 438,
  [SMALL_STATE(35)] = 442,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimiter, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimiter, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_expr_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_expr, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_expr, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_expr, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_expr, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [172] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_booklit(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
