// Code generated by pigeon; DO NOT EDIT.

package ast

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func ifaceStr(val interface{}) string {
	str := ""
	for _, seg := range val.([]interface{}) {
		str = str + string(seg.([]byte))
	}

	return str
}

func ifaceSequences(val interface{}) []Sequence {
	seq := []Sequence{}
	for _, node := range val.([]interface{}) {
		seq = append(seq, node.(Sequence))
	}

	return seq
}

func ifaceNodes(val interface{}) []Node {
	nodes := []Node{}
	for _, node := range val.([]interface{}) {
		nodes = append(nodes, node.(Node))
	}

	return nodes
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Booklit",
			pos:  position{line: 34, col: 1, offset: 581},
			expr: &actionExpr{
				pos: position{line: 34, col: 12, offset: 592},
				run: (*parser).callonBooklit1,
				expr: &seqExpr{
					pos: position{line: 34, col: 12, offset: 592},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 34, col: 12, offset: 592},
							label: "node",
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 17, offset: 597},
								name: "Paragraphs",
							},
						},
						&notExpr{
							pos: position{line: 34, col: 28, offset: 608},
							expr: &anyMatcher{
								line: 34, col: 29, offset: 609,
							},
						},
					},
				},
			},
		},
		{
			name: "Paragraphs",
			pos:  position{line: 38, col: 1, offset: 635},
			expr: &actionExpr{
				pos: position{line: 38, col: 15, offset: 649},
				run: (*parser).callonParagraphs1,
				expr: &seqExpr{
					pos: position{line: 38, col: 15, offset: 649},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 38, col: 15, offset: 649},
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 15, offset: 649},
								name: "CommentSpacing",
							},
						},
						&labeledExpr{
							pos:   position{line: 38, col: 31, offset: 665},
							label: "paragraphs",
							expr: &oneOrMoreExpr{
								pos: position{line: 38, col: 42, offset: 676},
								expr: &actionExpr{
									pos: position{line: 38, col: 43, offset: 677},
									run: (*parser).callonParagraphs7,
									expr: &seqExpr{
										pos: position{line: 38, col: 43, offset: 677},
										exprs: []interface{}{
											&labeledExpr{
												pos:   position{line: 38, col: 43, offset: 677},
												label: "p",
												expr: &ruleRefExpr{
													pos:  position{line: 38, col: 45, offset: 679},
													name: "Paragraph",
												},
											},
											&zeroOrMoreExpr{
												pos: position{line: 38, col: 55, offset: 689},
												expr: &ruleRefExpr{
													pos:  position{line: 38, col: 55, offset: 689},
													name: "CommentSpacing",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LineBreak",
			pos:  position{line: 42, col: 1, offset: 777},
			expr: &choiceExpr{
				pos: position{line: 42, col: 14, offset: 790},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 42, col: 14, offset: 790},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
					&litMatcher{
						pos:        position{line: 42, col: 21, offset: 797},
						val:        "\r\n",
						ignoreCase: false,
						want:       "\"\\r\\n\"",
					},
				},
			},
		},
		{
			name: "CommentSpacing",
			pos:  position{line: 44, col: 1, offset: 805},
			expr: &choiceExpr{
				pos: position{line: 44, col: 19, offset: 823},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 44, col: 19, offset: 823},
						name: "LineBreak",
					},
					&ruleRefExpr{
						pos:  position{line: 44, col: 31, offset: 835},
						name: "Comment",
					},
				},
			},
		},
		{
			name: "Paragraph",
			pos:  position{line: 46, col: 1, offset: 844},
			expr: &actionExpr{
				pos: position{line: 46, col: 14, offset: 857},
				run: (*parser).callonParagraph1,
				expr: &labeledExpr{
					pos:   position{line: 46, col: 14, offset: 857},
					label: "lines",
					expr: &oneOrMoreExpr{
						pos: position{line: 46, col: 20, offset: 863},
						expr: &actionExpr{
							pos: position{line: 46, col: 21, offset: 864},
							run: (*parser).callonParagraph4,
							expr: &seqExpr{
								pos: position{line: 46, col: 21, offset: 864},
								exprs: []interface{}{
									&labeledExpr{
										pos:   position{line: 46, col: 21, offset: 864},
										label: "l",
										expr: &ruleRefExpr{
											pos:  position{line: 46, col: 23, offset: 866},
											name: "Line",
										},
									},
									&zeroOrOneExpr{
										pos: position{line: 46, col: 28, offset: 871},
										expr: &ruleRefExpr{
											pos:  position{line: 46, col: 28, offset: 871},
											name: "LineBreak",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Line",
			pos:  position{line: 50, col: 1, offset: 954},
			expr: &actionExpr{
				pos: position{line: 50, col: 9, offset: 962},
				run: (*parser).callonLine1,
				expr: &seqExpr{
					pos: position{line: 50, col: 9, offset: 962},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 50, col: 9, offset: 962},
							expr: &charClassMatcher{
								pos:        position{line: 50, col: 9, offset: 962},
								val:        "[ \\t]",
								chars:      []rune{' ', '\t'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 50, col: 16, offset: 969},
							label: "words",
							expr: &oneOrMoreExpr{
								pos: position{line: 50, col: 22, offset: 975},
								expr: &ruleRefExpr{
									pos:  position{line: 50, col: 23, offset: 976},
									name: "Word",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 54, col: 1, offset: 1030},
			expr: &actionExpr{
				pos: position{line: 54, col: 9, offset: 1038},
				run: (*parser).callonWord1,
				expr: &seqExpr{
					pos: position{line: 54, col: 9, offset: 1038},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 54, col: 9, offset: 1038},
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 9, offset: 1038},
								name: "Comment",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 18, offset: 1047},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 54, col: 23, offset: 1052},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 54, col: 23, offset: 1052},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 54, col: 32, offset: 1061},
										name: "Invoke",
									},
									&ruleRefExpr{
										pos:  position{line: 54, col: 41, offset: 1070},
										name: "Interpolated",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 54, col: 55, offset: 1084},
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 55, offset: 1084},
								name: "Comment",
							},
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 58, col: 1, offset: 1116},
			expr: &seqExpr{
				pos: position{line: 58, col: 12, offset: 1127},
				exprs: []interface{}{
					&zeroOrMoreExpr{
						pos: position{line: 58, col: 12, offset: 1127},
						expr: &charClassMatcher{
							pos:        position{line: 58, col: 12, offset: 1127},
							val:        "[ \\t]",
							chars:      []rune{' ', '\t'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&litMatcher{
						pos:        position{line: 58, col: 19, offset: 1134},
						val:        "{-",
						ignoreCase: false,
						want:       "\"{-\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 58, col: 24, offset: 1139},
						expr: &choiceExpr{
							pos: position{line: 58, col: 25, offset: 1140},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 58, col: 25, offset: 1140},
									name: "Comment",
								},
								&seqExpr{
									pos: position{line: 58, col: 35, offset: 1150},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 58, col: 35, offset: 1150},
											expr: &litMatcher{
												pos:        position{line: 58, col: 36, offset: 1151},
												val:        "-}",
												ignoreCase: false,
												want:       "\"-}\"",
											},
										},
										&anyMatcher{
											line: 58, col: 41, offset: 1156,
										},
									},
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 58, col: 45, offset: 1160},
						val:        "-}",
						ignoreCase: false,
						want:       "\"-}\"",
					},
				},
			},
		},
		{
			name: "Interpolated",
			pos:  position{line: 60, col: 1, offset: 1166},
			expr: &actionExpr{
				pos: position{line: 60, col: 17, offset: 1182},
				run: (*parser).callonInterpolated1,
				expr: &seqExpr{
					pos: position{line: 60, col: 17, offset: 1182},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 60, col: 17, offset: 1182},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 21, offset: 1186},
							label: "word",
							expr: &zeroOrOneExpr{
								pos: position{line: 60, col: 26, offset: 1191},
								expr: &ruleRefExpr{
									pos:  position{line: 60, col: 26, offset: 1191},
									name: "Word",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 60, col: 32, offset: 1197},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "WrappedLine",
			pos:  position{line: 68, col: 1, offset: 1288},
			expr: &actionExpr{
				pos: position{line: 68, col: 16, offset: 1303},
				run: (*parser).callonWrappedLine1,
				expr: &seqExpr{
					pos: position{line: 68, col: 16, offset: 1303},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 68, col: 16, offset: 1303},
							label: "firstWord",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 26, offset: 1313},
								name: "Word",
							},
						},
						&labeledExpr{
							pos:   position{line: 68, col: 31, offset: 1318},
							label: "words",
							expr: &zeroOrMoreExpr{
								pos: position{line: 68, col: 37, offset: 1324},
								expr: &choiceExpr{
									pos: position{line: 68, col: 38, offset: 1325},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 68, col: 38, offset: 1325},
											name: "Word",
										},
										&ruleRefExpr{
											pos:  position{line: 68, col: 45, offset: 1332},
											name: "Split",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Split",
			pos:  position{line: 73, col: 1, offset: 1463},
			expr: &actionExpr{
				pos: position{line: 73, col: 10, offset: 1472},
				run: (*parser).callonSplit1,
				expr: &seqExpr{
					pos: position{line: 73, col: 10, offset: 1472},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 73, col: 10, offset: 1472},
							name: "LineBreak",
						},
						&zeroOrMoreExpr{
							pos: position{line: 73, col: 20, offset: 1482},
							expr: &charClassMatcher{
								pos:        position{line: 73, col: 20, offset: 1482},
								val:        "[ \\t]",
								chars:      []rune{' ', '\t'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 75, col: 1, offset: 1518},
			expr: &choiceExpr{
				pos: position{line: 75, col: 11, offset: 1528},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 75, col: 11, offset: 1528},
						run: (*parser).callonString2,
						expr: &labeledExpr{
							pos:   position{line: 75, col: 11, offset: 1528},
							label: "str",
							expr: &oneOrMoreExpr{
								pos: position{line: 75, col: 15, offset: 1532},
								expr: &charClassMatcher{
									pos:        position{line: 75, col: 15, offset: 1532},
									val:        "[^\\\\{}\\r\\n]",
									chars:      []rune{'\\', '{', '}', '\r', '\n'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 75, col: 61, offset: 1578},
						run: (*parser).callonString6,
						expr: &seqExpr{
							pos: position{line: 75, col: 61, offset: 1578},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 75, col: 61, offset: 1578},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&charClassMatcher{
									pos:        position{line: 75, col: 66, offset: 1583},
									val:        "[\\\\{}]",
									chars:      []rune{'\\', '{', '}'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "VerbatimString",
			pos:  position{line: 77, col: 1, offset: 1626},
			expr: &choiceExpr{
				pos: position{line: 77, col: 19, offset: 1644},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 77, col: 19, offset: 1644},
						run: (*parser).callonVerbatimString2,
						expr: &labeledExpr{
							pos:   position{line: 77, col: 19, offset: 1644},
							label: "str",
							expr: &oneOrMoreExpr{
								pos: position{line: 77, col: 23, offset: 1648},
								expr: &charClassMatcher{
									pos:        position{line: 77, col: 23, offset: 1648},
									val:        "[^\\r\\n}]",
									chars:      []rune{'\r', '\n', '}'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 79, col: 5, offset: 1693},
						run: (*parser).callonVerbatimString6,
						expr: &seqExpr{
							pos: position{line: 79, col: 5, offset: 1693},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 79, col: 5, offset: 1693},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
								&notExpr{
									pos: position{line: 79, col: 9, offset: 1697},
									expr: &litMatcher{
										pos:        position{line: 79, col: 10, offset: 1698},
										val:        "}}",
										ignoreCase: false,
										want:       "\"}}\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PreformattedBlockLine",
			pos:  position{line: 83, col: 1, offset: 1737},
			expr: &actionExpr{
				pos: position{line: 83, col: 26, offset: 1762},
				run: (*parser).callonPreformattedBlockLine1,
				expr: &seqExpr{
					pos: position{line: 83, col: 26, offset: 1762},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 83, col: 26, offset: 1762},
							label: "indent",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 33, offset: 1769},
								name: "Indent",
							},
						},
						&labeledExpr{
							pos:   position{line: 83, col: 40, offset: 1776},
							label: "words",
							expr: &zeroOrMoreExpr{
								pos: position{line: 83, col: 46, offset: 1782},
								expr: &ruleRefExpr{
									pos:  position{line: 83, col: 46, offset: 1782},
									name: "Word",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 52, offset: 1788},
							name: "LineBreak",
						},
					},
				},
			},
		},
		{
			name: "PreformattedBlock",
			pos:  position{line: 89, col: 1, offset: 1918},
			expr: &actionExpr{
				pos: position{line: 89, col: 22, offset: 1939},
				run: (*parser).callonPreformattedBlock1,
				expr: &seqExpr{
					pos: position{line: 89, col: 22, offset: 1939},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 89, col: 22, offset: 1939},
							name: "LineBreak",
						},
						&labeledExpr{
							pos:   position{line: 89, col: 32, offset: 1949},
							label: "lines",
							expr: &zeroOrMoreExpr{
								pos: position{line: 89, col: 38, offset: 1955},
								expr: &ruleRefExpr{
									pos:  position{line: 89, col: 38, offset: 1955},
									name: "PreformattedBlockLine",
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 89, col: 61, offset: 1978},
							expr: &charClassMatcher{
								pos:        position{line: 89, col: 61, offset: 1978},
								val:        "[ \\t]",
								chars:      []rune{' ', '\t'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "VerbatimLine",
			pos:  position{line: 94, col: 1, offset: 2079},
			expr: &actionExpr{
				pos: position{line: 94, col: 17, offset: 2095},
				run: (*parser).callonVerbatimLine1,
				expr: &labeledExpr{
					pos:   position{line: 94, col: 17, offset: 2095},
					label: "words",
					expr: &zeroOrMoreExpr{
						pos: position{line: 94, col: 23, offset: 2101},
						expr: &ruleRefExpr{
							pos:  position{line: 94, col: 23, offset: 2101},
							name: "VerbatimString",
						},
					},
				},
			},
		},
		{
			name: "VerbatimBlockLine",
			pos:  position{line: 98, col: 1, offset: 2164},
			expr: &actionExpr{
				pos: position{line: 98, col: 22, offset: 2185},
				run: (*parser).callonVerbatimBlockLine1,
				expr: &seqExpr{
					pos: position{line: 98, col: 22, offset: 2185},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 98, col: 22, offset: 2185},
							label: "indent",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 29, offset: 2192},
								name: "Indent",
							},
						},
						&labeledExpr{
							pos:   position{line: 98, col: 36, offset: 2199},
							label: "words",
							expr: &zeroOrMoreExpr{
								pos: position{line: 98, col: 42, offset: 2205},
								expr: &ruleRefExpr{
									pos:  position{line: 98, col: 42, offset: 2205},
									name: "VerbatimString",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 58, offset: 2221},
							name: "LineBreak",
						},
					},
				},
			},
		},
		{
			name: "VerbatimBlock",
			pos:  position{line: 104, col: 1, offset: 2351},
			expr: &actionExpr{
				pos: position{line: 104, col: 18, offset: 2368},
				run: (*parser).callonVerbatimBlock1,
				expr: &seqExpr{
					pos: position{line: 104, col: 18, offset: 2368},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 104, col: 18, offset: 2368},
							name: "LineBreak",
						},
						&labeledExpr{
							pos:   position{line: 104, col: 28, offset: 2378},
							label: "lines",
							expr: &zeroOrMoreExpr{
								pos: position{line: 104, col: 34, offset: 2384},
								expr: &ruleRefExpr{
									pos:  position{line: 104, col: 34, offset: 2384},
									name: "VerbatimBlockLine",
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 104, col: 53, offset: 2403},
							expr: &charClassMatcher{
								pos:        position{line: 104, col: 53, offset: 2403},
								val:        "[ \\t]",
								chars:      []rune{' ', '\t'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Invoke",
			pos:  position{line: 109, col: 1, offset: 2504},
			expr: &actionExpr{
				pos: position{line: 109, col: 11, offset: 2514},
				run: (*parser).callonInvoke1,
				expr: &seqExpr{
					pos: position{line: 109, col: 11, offset: 2514},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 109, col: 11, offset: 2514},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 16, offset: 2519},
							label: "name",
							expr: &oneOrMoreExpr{
								pos: position{line: 109, col: 22, offset: 2525},
								expr: &charClassMatcher{
									pos:        position{line: 109, col: 22, offset: 2525},
									val:        "[a-z-]",
									chars:      []rune{'-'},
									ranges:     []rune{'a', 'z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 109, col: 31, offset: 2534},
							label: "args",
							expr: &zeroOrMoreExpr{
								pos: position{line: 109, col: 37, offset: 2540},
								expr: &ruleRefExpr{
									pos:  position{line: 109, col: 37, offset: 2540},
									name: "Argument",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "VerbatimArg",
			pos:  position{line: 122, col: 1, offset: 2756},
			expr: &actionExpr{
				pos: position{line: 122, col: 16, offset: 2771},
				run: (*parser).callonVerbatimArg1,
				expr: &seqExpr{
					pos: position{line: 122, col: 16, offset: 2771},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 122, col: 16, offset: 2771},
							val:        "{{{",
							ignoreCase: false,
							want:       "\"{{{\"",
						},
						&labeledExpr{
							pos:   position{line: 122, col: 22, offset: 2777},
							label: "node",
							expr: &choiceExpr{
								pos: position{line: 122, col: 28, offset: 2783},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 122, col: 28, offset: 2783},
										name: "VerbatimBlock",
									},
									&ruleRefExpr{
										pos:  position{line: 122, col: 44, offset: 2799},
										name: "VerbatimLine",
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 122, col: 58, offset: 2813},
							val:        "}}}",
							ignoreCase: false,
							want:       "\"}}}\"",
						},
					},
				},
			},
		},
		{
			name: "PreformattedArg",
			pos:  position{line: 126, col: 1, offset: 2843},
			expr: &actionExpr{
				pos: position{line: 126, col: 20, offset: 2862},
				run: (*parser).callonPreformattedArg1,
				expr: &seqExpr{
					pos: position{line: 126, col: 20, offset: 2862},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 126, col: 20, offset: 2862},
							val:        "{{",
							ignoreCase: false,
							want:       "\"{{\"",
						},
						&labeledExpr{
							pos:   position{line: 126, col: 25, offset: 2867},
							label: "node",
							expr: &ruleRefExpr{
								pos:  position{line: 126, col: 30, offset: 2872},
								name: "PreformattedBlock",
							},
						},
						&litMatcher{
							pos:        position{line: 126, col: 48, offset: 2890},
							val:        "}}",
							ignoreCase: false,
							want:       "\"}}\"",
						},
					},
				},
			},
		},
		{
			name: "EmptyArg",
			pos:  position{line: 130, col: 1, offset: 2919},
			expr: &actionExpr{
				pos: position{line: 130, col: 13, offset: 2931},
				run: (*parser).callonEmptyArg1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 130, col: 13, offset: 2931},
					expr: &ruleRefExpr{
						pos:  position{line: 130, col: 13, offset: 2931},
						name: "CommentSpacing",
					},
				},
			},
		},
		{
			name: "Arg",
			pos:  position{line: 132, col: 1, offset: 2968},
			expr: &actionExpr{
				pos: position{line: 132, col: 8, offset: 2975},
				run: (*parser).callonArg1,
				expr: &seqExpr{
					pos: position{line: 132, col: 8, offset: 2975},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 132, col: 8, offset: 2975},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 12, offset: 2979},
							label: "node",
							expr: &zeroOrOneExpr{
								pos: position{line: 132, col: 17, offset: 2984},
								expr: &choiceExpr{
									pos: position{line: 132, col: 18, offset: 2985},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 132, col: 18, offset: 2985},
											name: "WrappedLine",
										},
										&ruleRefExpr{
											pos:  position{line: 132, col: 32, offset: 2999},
											name: "ParaArg",
										},
										&ruleRefExpr{
											pos:  position{line: 132, col: 42, offset: 3009},
											name: "EmptyArg",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 132, col: 53, offset: 3020},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "ParaArg",
			pos:  position{line: 140, col: 1, offset: 3111},
			expr: &actionExpr{
				pos: position{line: 140, col: 12, offset: 3122},
				run: (*parser).callonParaArg1,
				expr: &seqExpr{
					pos: position{line: 140, col: 12, offset: 3122},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 140, col: 12, offset: 3122},
							label: "paras",
							expr: &ruleRefExpr{
								pos:  position{line: 140, col: 18, offset: 3128},
								name: "Paragraphs",
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 140, col: 29, offset: 3139},
							expr: &charClassMatcher{
								pos:        position{line: 140, col: 29, offset: 3139},
								val:        "[ \\t]",
								chars:      []rune{' ', '\t'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Argument",
			pos:  position{line: 144, col: 1, offset: 3171},
			expr: &choiceExpr{
				pos: position{line: 144, col: 13, offset: 3183},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 144, col: 13, offset: 3183},
						name: "VerbatimArg",
					},
					&ruleRefExpr{
						pos:  position{line: 144, col: 27, offset: 3197},
						name: "PreformattedArg",
					},
					&ruleRefExpr{
						pos:  position{line: 144, col: 45, offset: 3215},
						name: "Arg",
					},
				},
			},
		},
		{
			name: "Indent",
			pos:  position{line: 146, col: 1, offset: 3220},
			expr: &actionExpr{
				pos: position{line: 146, col: 11, offset: 3230},
				run: (*parser).callonIndent1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 146, col: 11, offset: 3230},
					expr: &charClassMatcher{
						pos:        position{line: 146, col: 11, offset: 3230},
						val:        "[ \\t]",
						chars:      []rune{' ', '\t'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
	},
}

func (c *current) onBooklit1(node interface{}) (interface{}, error) {
	return node, nil
}

func (p *parser) callonBooklit1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooklit1(stack["node"])
}

func (c *current) onParagraphs7(p interface{}) (interface{}, error) {
	return p, nil
}

func (p *parser) callonParagraphs7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParagraphs7(stack["p"])
}

func (c *current) onParagraphs1(paragraphs interface{}) (interface{}, error) {
	return Sequence(ifaceNodes(paragraphs)), nil
}

func (p *parser) callonParagraphs1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParagraphs1(stack["paragraphs"])
}

func (c *current) onParagraph4(l interface{}) (interface{}, error) {
	return l, nil
}

func (p *parser) callonParagraph4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParagraph4(stack["l"])
}

func (c *current) onParagraph1(lines interface{}) (interface{}, error) {
	return Paragraph(ifaceSequences(lines)), nil
}

func (p *parser) callonParagraph1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParagraph1(stack["lines"])
}

func (c *current) onLine1(words interface{}) (interface{}, error) {
	return Sequence(ifaceNodes(words)), nil
}

func (p *parser) callonLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLine1(stack["words"])
}

func (c *current) onWord1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1(stack["val"])
}

func (c *current) onInterpolated1(word interface{}) (interface{}, error) {
	if word == nil {
		return Sequence{}, nil
	} else {
		return word, nil
	}
}

func (p *parser) callonInterpolated1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInterpolated1(stack["word"])
}

func (c *current) onWrappedLine1(firstWord, words interface{}) (interface{}, error) {
	allWords := append([]interface{}{firstWord}, words.([]interface{})...)
	return Sequence(ifaceNodes(allWords)), nil
}

func (p *parser) callonWrappedLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWrappedLine1(stack["firstWord"], stack["words"])
}

func (c *current) onSplit1() (interface{}, error) {
	return String(" "), nil
}

func (p *parser) callonSplit1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSplit1()
}

func (c *current) onString2(str interface{}) (interface{}, error) {
	return String(c.text), nil
}

func (p *parser) callonString2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString2(stack["str"])
}

func (c *current) onString6() (interface{}, error) {
	return String(c.text[1:]), nil
}

func (p *parser) callonString6() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString6()
}

func (c *current) onVerbatimString2(str interface{}) (interface{}, error) {
	return String(c.text), nil
}

func (p *parser) callonVerbatimString2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVerbatimString2(stack["str"])
}

func (c *current) onVerbatimString6() (interface{}, error) {
	return String(c.text), nil
}

func (p *parser) callonVerbatimString6() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVerbatimString6()
}

func (c *current) onPreformattedBlockLine1(indent, words interface{}) (interface{}, error) {
	line := []Node{String(indent.(string))}
	line = append(line, ifaceNodes(words)...)
	return Sequence(line), nil
}

func (p *parser) callonPreformattedBlockLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreformattedBlockLine1(stack["indent"], stack["words"])
}

func (c *current) onPreformattedBlock1(lines interface{}) (interface{}, error) {
	delete(c.globalStore, "indent-skip")
	return Preformatted(ifaceSequences(lines)), nil
}

func (p *parser) callonPreformattedBlock1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreformattedBlock1(stack["lines"])
}

func (c *current) onVerbatimLine1(words interface{}) (interface{}, error) {
	return Sequence(ifaceNodes(words)), nil
}

func (p *parser) callonVerbatimLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVerbatimLine1(stack["words"])
}

func (c *current) onVerbatimBlockLine1(indent, words interface{}) (interface{}, error) {
	line := []Node{String(indent.(string))}
	line = append(line, ifaceNodes(words)...)
	return Sequence(line), nil
}

func (p *parser) callonVerbatimBlockLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVerbatimBlockLine1(stack["indent"], stack["words"])
}

func (c *current) onVerbatimBlock1(lines interface{}) (interface{}, error) {
	delete(c.globalStore, "indent-skip")
	return Preformatted(ifaceSequences(lines)), nil
}

func (p *parser) callonVerbatimBlock1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVerbatimBlock1(stack["lines"])
}

func (c *current) onInvoke1(name, args interface{}) (interface{}, error) {
	return Invoke{
		Function:  ifaceStr(name),
		Arguments: ifaceNodes(args),

		Location: Location{
			Line:   c.pos.line,
			Col:    c.pos.col,
			Offset: c.pos.offset,
		},
	}, nil
}

func (p *parser) callonInvoke1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInvoke1(stack["name"], stack["args"])
}

func (c *current) onVerbatimArg1(node interface{}) (interface{}, error) {
	return node, nil
}

func (p *parser) callonVerbatimArg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVerbatimArg1(stack["node"])
}

func (c *current) onPreformattedArg1(node interface{}) (interface{}, error) {
	return node, nil
}

func (p *parser) callonPreformattedArg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreformattedArg1(stack["node"])
}

func (c *current) onEmptyArg1() (interface{}, error) {
	return nil, nil
}

func (p *parser) callonEmptyArg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptyArg1()
}

func (c *current) onArg1(node interface{}) (interface{}, error) {
	if node == nil {
		return String(""), nil
	} else {
		return node, nil
	}
}

func (p *parser) callonArg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArg1(stack["node"])
}

func (c *current) onParaArg1(paras interface{}) (interface{}, error) {
	return paras, nil
}

func (p *parser) callonParaArg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParaArg1(stack["paras"])
}

func (c *current) onIndent1() (interface{}, error) {
	skip := len(c.text)

	i, found := c.globalStore["indent-skip"]
	if found {
		skip = i.(int)
	} else {
		c.globalStore["indent-skip"] = skip
	}

	if skip <= len(c.text) {
		return string(c.text[skip:]), nil
	} else {
		return "", nil
	}
}

func (p *parser) callonIndent1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndent1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
