#!/bin/bash

set -e -u

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <src> -- <booklit args...>" >&2
  exit 1
fi

src=$1
shift

out=$PWD/docs

cd $src

go run ./cmd/booklit \
  -i docs/lit/index.lit \
  -o $out \
  --html-templates docs/html \
  --plugin github.com/vito/booklit/docs/go \
  --plugin github.com/vito/booklit/chroma/plugin \
  "$@"
