#!/bin/bash

out=$PWD/docs

cd $(dirname $0)/..

go run ./cmd/booklit \
  -i docs/lit/index.lit \
  -o $out \
  --html-templates docs/html \
  --plugin github.com/vito/booklit/docs/go \
  --plugin github.com/vito/booklit/chroma/plugin \
  "$@"
