#!/bin/bash

go run cmd/booklit/*.go \
  -i docs/lit/index.lit \
  -o docs \
  --html-templates docs/lit/html \
  --plugin github.com/vito/booklit/booklitdoc \
  --plugin github.com/vito/booklit/chroma/plugin \
  "$@"
