#!/bin/bash

set -e -u

export GOPATH=$PWD/depspath:$PWD/gopath
export PATH=$PWD/depspath/bin:$PWD/gopath/bin:$PATH

cd gopath/src/github.com/vito/booklit

echo "fetching dependencies..."
go get -t -d ./...

echo "installing ginkgo..."
go install github.com/onsi/ginkgo/ginkgo

function emit_coveralls() {
  if [ -n "$COVERALLS_TOKEN" ]; then
    echo "emitting code coverage..."
    go get github.com/mattn/goveralls
    goveralls -service concourse \
      -coverprofile <(find . -name '*.coverprofile' | xargs cat | grep -v 'booklit.peg.go\|render/bindata.go')
  fi
}

trap emit_coveralls EXIT

echo "running tests..."
ginkgo -r -p \
  -cover \
  -coverpkg $(go list ./... | grep -v /cmd/ | xargs echo | tr ' ' ',') \
  -covermode atomic \
  "$@"
